### ISSUE TITLE
Doesn't work with Lumen?

### ISSUE THREAD

**Issue by muhammadnm** [Propaganistas/Laravel-Intl#5]
I tried to make this work with Lumen (5.5.1) (Laravel Components 5.5.*)

Registered provider in bootstrap/app.php
`$app->register(Propaganistas\LaravelIntl\IntlServiceProvider::class);`

Throws me this error
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Lumen\Application::booted() in SRC\lumen\vendor\propaganistas\laravel-intl\src\IntlServiceProvider.php:119
Stack trace:
#0 SRC\lumen\vendor\propaganistas\laravel-intl\src\IntlServiceProvider.php(25): Propaganistas\LaravelIntl\IntlServiceProvider->registerDateHandler()

#1 SRC\lumen\vendor\laravel\lumen-framework\src\Application.php(193): Propaganistas\LaravelIntl\IntlServiceProvider->register()

#2 SRC\lumen\bootstrap\app.php(84): Laravel\Lumen\Application->register(Object(Propaganistas\LaravelIntl\IntlServiceProvider))

#3 SRC\lumen\public\index.php(14): require('S:\\xampp\\htdocs...')

#4 {main} thrown in SRC\lumen\vendor\propaganistas\laravel-intl\src\IntlServiceProvider.php on line 119
```

**Comment by Propaganistas** [comment]
The README doesn't claim to support Lumen. Please feel free to resolve any Lumen-related incompatibilities.

**Comment by muhammadnm** [comment]
Hii I added lumen fix here
https://github.com/muhammadnm/Laravel-Intl/commit/144103f650f17faaea87c953135ec526986e6e6f

Let me know if that's correct or need any other fixed?
